table 'Attended Bridge'
	lineageTag: a567913b-4536-41d7-94ff-37687f8f0960

	column Attended
		dataType: int64
		formatString: 0
		lineageTag: a2765ef5-cc2d-41e4-a0e4-f7a8373ebab0
		summarizeBy: none
		sourceColumn: Attended

		annotation SummarizationSetBy = Automatic

	column YN
		dataType: string
		lineageTag: 2732366b-f88e-4c92-bce5-bbf6f4f849ac
		summarizeBy: none
		sourceColumn: YN

		annotation SummarizationSetBy = Automatic

	partition 'Attended Bridge-35c78ede-0edc-44fe-a24f-d133cc25fafa' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUYpMLVaK1YlWMgCy/fKVYmMB", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [StoreManagementExperience = _t, YN = _t]),
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"StoreManagementExperience", "Attended"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Attended", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

